name: Lint

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  lint: 
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js 18.16.0
        uses: actions/setup-node@v3
        with: 
          node-version: 18.16.0
      
      - name: Install pnpm
        run: npm i -g pnpm
      
      - name: Install Dependencies
        run: |
          pnpm install
          pnpm -r run build

      - name: NpmPkgJsonLint
        run: pnpm run npmPkgJsonLint

      - name: ESLint
        run: pnpm run eslint

 
  typecheck: 
    name: Typecheck
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js 18.16.0
        uses: actions/setup-node@v3
        with: 
          node-version: 18.16.0
      
      - name: Install pnpm
        run: npm i -g pnpm
      
      - name: Install Dependencies
        run: pnpm install
      
      - name: Build
        run: pnpm run -r build
        
      - name: Typecheck
        run: pnpm -r run typecheck
          