name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  pages: write
  discussions: write
  issues: write
  checks: write
  actions: write
  statuses: write

jobs:
  eslint: 
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      
      - name: Install pnpm
        run: npm i -g pnpm
      
      - name: Install Dependencies
        run: pnpm install
      
      - name: ESLint
        run: pnpm run eslint
  
  typecheck: 
    name: Typecheck
    runs-on: ubuntu-latest
    needs: [eslint]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      
      - name: Install pnpm
        run: npm i -g pnpm
      
      - name: Install Dependencies
        run: pnpm install
      
      - name: Typecheck
        run: pnpm run typecheck
    
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [typecheck]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm 
        run: npm -g i pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'chore: version package and publish'
          title: 'chore: version package and publish'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        run: echo "A new version of ${GITHUB_REPOSITORY} was published" # my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
